import os
import requests
import json
import asyncio
from fastapi import FastAPI, Request, BackgroundTasks
from telegram import Bot, Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes, CallbackQueryHandler
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Config
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
WP_URL = os.getenv("WP_URL") # e.g. https://site.locl.lt/wp-json/clawwp/v1
WP_USERNAME = os.getenv("WP_USERNAME")
WP_APP_PASSWORD = os.getenv("WP_APP_PASSWORD")
AI_PROVIDER_KEY = os.getenv("AI_PROVIDER_KEY") # Anthropic or OpenAI

app = FastAPI(title="WPMaster AI Brain")

# Initialize Telegram Bot for sending messages
bot = Bot(token=TELEGRAM_TOKEN)

# In-memory store for pending approvals (Use Redis for production)
pending_approvals = {}

async def call_wp_tool(tool: str, params: dict):
    """Calls the WordPress Gateway Plugin REST API."""
    url = f"{WP_URL}/tools"
    auth = (WP_USERNAME, WP_APP_PASSWORD)
    payload = {
        "tool": tool,
        "params": params
    }
    
    response = requests.post(url, json=payload, auth=auth)
    return response.json()

async def model_router(prompt: str, task_type: str = "general"):
    """
    Routes the task to the appropriate AI model.
    - Routine: Gemini 1.5 Flash
    - Complex/Visual: Claude 3.5 Sonnet / GPT-4o
    """
    # For POC, we'll use a simplified routing logic.
    # In production, you would call Gemini or Claude here.
    print(f"Routing task: {prompt} (Type: {task_type})")
    
    # Placeholder for AI response logic
    # Here you would call your chosen AI API
    return {
        "title": "Staged Content from AI",
        "content": f"<p>This content was generated by {task_type} model for: {prompt}</p>",
        "excerpt": "AI generated summary..."
    }

async def handle_telegram_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Main Telegram entry point."""
    user_msg = update.message.text
    chat_id = update.effective_chat.id
    
    await update.message.reply_text("🤖 Processing your request... (Routing to Brain)")
    
    # 1. Route to AI Brain
    ai_content = await model_router(user_msg)
    
    # 2. Call WP Gateway to create DRAFT
    wp_result = await call_wp_tool("manage_posts", {
        "action": "create",
        "title": ai_content["title"],
        "content": ai_content["content"]
    })
    
    if "error" in wp_result:
        await update.message.reply_text(f"❌ WP Error: {wp_result['error']}")
        return

    post_id = wp_result["post_id"]
    preview_url = wp_result.get("url")

    # 3. Store for approval
    pending_approvals[chat_id] = {
        "post_id": post_id,
        "content": ai_content
    }

    # 4. Request Approval with Buttons
    keyboard = [
        [
            InlineKeyboardButton("✅ Publish Now", callback_data=f"publish_{post_id}"),
            InlineKeyboardButton("🗑️ Discard", callback_data=f"discard_{post_id}")
        ]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    
    await update.message.reply_text(
        f"📝 **Draft Created!**\n\n"
        f"Title: {ai_content['title']}\n"
        f"Preview: {preview_url}\n\n"
        f"Should I publish this to your site?",
        reply_markup=reply_markup,
        parse_mode="Markdown"
    )

async def button_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handles 'Publish' or 'Discard' button clicks."""
    query = update.callback_query
    await query.answer()
    
    data = query.data
    chat_id = update.effective_chat.id
    
    if data.startswith("publish_"):
        post_id = data.split("_")[1]
        # Update WP status to 'publish'
        result = await call_wp_tool("manage_posts", {
            "action": "edit",
            "post_id": int(post_id),
            "status": "publish"
        })
        
        if "success" in result:
            await query.edit_message_text(text=f"🚀 **Success!** Post #{post_id} is now LIVE.")
        else:
            await query.edit_message_text(text=f"❌ Failed to publish: {result.get('error')}")
            
    elif data.startswith("discard_"):
        await query.edit_message_text(text="🗑️ Draft discarded.")

@app.get("/")
async def root():
    return {
        "message": "WPMaster AI Brain is Online",
        "status": "active",
        "endpoints": {
            "health": "/health",
            "webhook": "/webhook/telegram"
        }
    }

@app.get("/health")
async def health():
    return {"status": "brain_online"}

@app.post("/webhook/telegram")
async def telegram_webhook(request: Request):
    """Webhook endpoint for Telegram."""
    data = await request.json()
    # In production, use the python-telegram-bot webhook handler
    # For POC, we'll assume the polling app is running separately or triggered here.
    return {"ok": True}

# Initialize Telegram Application
# Note: For Render, we usually run the polling bot in a separate process or use webhooks.
if __name__ == "__main__":
    import uvicorn
    # This part is just for local testing
    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", 8000)))
